version: '3'

services:
  database:
    container_name: database
    restart: always
    image: mongo
    ports:
      - "4000:27017"
    volumes:
      - ./database_data:/data/db

  backend:
    container_name: backend
    restart: always
    build: ./Server/code
    image:  marved_backend_p1_201905554
    ports:
      - "5000:3000"
    depends_on:
      - database
    links:
      - database